---
## Registry VM setup with CentOS
- name:  Launch VMs for OCP -- ACM 
  hosts: baremetal
  become: true
  vars_files:
    - vminfo.yaml

  tasks:
    # Copy CentOS image to KVM
    - name: Copy images 
      ansible.builtin.copy:
        src: CentOS-Stream-GenericCloud-9-20220718.0.x86_64.qcow2
        dest: /var/lib/libvirt/images/{{ item.nodename }}.qcow2
      loop: "{{ registry }}"
    
    - name: Copy cloud-init images 
      ansible.builtin.copy:
        src: cloud-init/init.iso
        dest: /var/lib/libvirt/images/init.iso

    # Create QEMU image for VMs
    - name: Resize the centos image
      command: 'qemu-img resize /var/lib/libvirt/images/{{ item.nodename }}.qcow2 500G'
      register: qcowcreation
      loop: "{{ registry }}"
    - debug:
        var: qcowcreation.msg

    # Define VMs
    - name: Define vm from xml and set autostart for Registry
      vars:
        nodename: "{{ item.nodename }}"
        mac: "{{ item.mac }}"
      community.libvirt.virt:
        command: define
        xml: "{{ lookup('template', 'vm_registry.xml.j2') }}"
        autostart: yes
      loop: "{{ registry }}"

    # Listing VMs
    - name: List all VMs
      community.libvirt.virt:
        command: list_vms
      register: all_vms
    - debug:
        msg: "{{ all_vms }}"
  
